version: "3.8"
services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile.fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./fuseki_data:/fuseki
    environment:
      - ADMIN_PASSWORD=adminpassword
    restart: always


  streamlit:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./:/app  # Mount your local code to the container
    depends_on:
      - fuseki
    restart: always


# This builds the ontology file
# sudo docker run -ti --rm -v `pwd`/data/ontologies:/usr/local/widoco/in:Z -v `pwd`/target/generated-doc:/usr/local/widoco/out:Z ghcr.io/dgarijo/widoco:v1.4.23 -ontFile in/wirr_project3.rdf -outFolder out -rewriteAll