version: "3.8"
services:
  fuseki:
    build:
      context: .
      dockerfile: Dockerfile.fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      - ./fuseki_data:/fuseki
    environment:
      - ADMIN_PASSWORD=adminpassword
    restart: always

  streamlit:
    build: .
    container_name: streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./:/app  # Mount your local code to the container
    depends_on:
      - fuseki
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./data/target/generated-doc:/usr/share/nginx/html:ro
    restart: always

  wpmongo:
    container_name: webprotege-mongodb
    image: mongo:4.1-bionic
    restart: unless-stopped
    volumes: 
      - ./.protegedata/mongodb:/data/db

  webprotege:
    container_name: webprotege
    image: protegeproject/webprotege
    depends_on:
      - wpmongo
    restart: unless-stopped
    environment:
      - webprotege.mongodb.host=wpmongo
    volumes: 
    - ./.protegedata/protege:/srv/webprotege
    ports:
      - 5000:8080


# if fuseki cant write
#mkdir -p fuseki_data
#chmod -R 777 fuseki_data

# sudo docker run -ti --rm -v `pwd`/data/ontologies:/usr/local/widoco/in:Z -v `pwd`/data/target/generated-doc:/usr/local/widoco/out:Z ghcr.io/dgarijo/widoco:v1.4.23 -ontFile in/wirr_project3.rdf -outFolder out -rewriteAll -webVowl
